name: Build, Push Docker Image & Run Container

on:
  push:
    branches:
      - master  # Trigger the workflow on push to 'master' branch (or 'main' if that's your default)

jobs:
  build:
    runs-on: ubuntu-latest  # Run on an Ubuntu machine

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Set up Docker Buildx for multi-platform builds

    - name: Log in to DockerHub
      uses: docker/login-action@v3  # Log in to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from secrets

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-vite-app .  # Build Docker image with the correct name

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/react-vite-app:latest  # Push the built image to Docker Hub

    - name: Run Docker container (optional)
      run: |
        docker run -d --name react-vite-app -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/react-vite-app:latest
        docker ps  # To verify that the container is running
